/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ActionButton({ text, bgColor }) {
  return (
    <button
      className={`px-16 py-7 mt-12 max-w-full ${bgColor} rounded-2xl w-[695px] max-md:px-5 max-md:mt-10`}
    >
      {text}
    </button>
  );
}

export default ActionButton;
