import Wallet from './Wallet.jsx'
import Register from './Register.jsx'
import NotFound from './NotFound.jsx'
import AddRecords from './AddRecords.jsx'
import BloodReport from './BloodReport.jsx'
import Diagnosis from './Diagnosis.jsx'
import PhysicalCheckup from './PhysicalCheckup.jsx'
import Dashboard from './Dashboard.jsx'
import ViewRequests from './ViewRequests.jsx'
export {Wallet, Register, ViewRequests, Dashboard, NotFound, AddRecords, BloodReport, Diagnosis, PhysicalCheckup}