import Wallet from './Wallet.jsx'
import Register from './Register.jsx'
import NotFound from './NotFound.jsx'
import AddRecords from './AddRecords.jsx'
import BloodReport from './BloodReport.jsx'
import Diagnosis from './Diagnosis.jsx'
import PhysicalCheckup from './PhysicalCheckup.jsx'
import Dashboard from './Dashboard.jsx'
import ViewRequests from './ViewRequests.jsx'
import Request from './Request.jsx'
import Navbar from './Navbar.jsx'
import ViewRecords from './ViewRecords.jsx'
import ResearcherDashboard from './ResearcherDashboard.jsx'
export {Wallet,Navbar, Register, ViewRequests,ViewRecords, Request, Dashboard, ResearcherDashboard, NotFound, AddRecords, BloodReport, Diagnosis, PhysicalCheckup}